# pytorch_lightning==2.0.1
# Contains best parameters determined in grid search
seed_everything: 0
optimizer: 
  class_path: torch.optim.AdamW
  init_args:
    lr: 0.01
model:
  class_path: UTAELightningRabina
  init_args:
    n_channels: 40
    temporal_position_mode: "relative"
    pos_class_weight: 50
    loss_function: "Focal"
    encoder_weights: pastis
    pretrained_checkpoint_path: "/share/home/e2406754/cde_mt/WildfireSpreadTSPlus/src/models/utae_paps_models/model.pth.tar" #this is used when encoder_weight=Pastis
do_train: true
do_test: true
do_predict: false